-- RakshaCover - Module Guardian Schema Extension
-- Run this AFTER the main db_schema.sql

-- 1. Guardian Links Table
-- Stores the connection between a vulnerable user (parent) and their tech-savvy guardian.
CREATE TABLE IF NOT EXISTS public.guardian_links (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    parent_user_id TEXT NOT NULL, -- In a real app, this would be a UUID referencing auth.users
    guardian_email TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'active', 'unlinked'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast lookups by parent_user_id
CREATE INDEX IF NOT EXISTS idx_guardian_links_parent ON public.guardian_links(parent_user_id);
CREATE INDEX IF NOT EXISTS idx_guardian_links_email ON public.guardian_links(guardian_email);

-- 2. Guardian Alerts Table
-- Stores the alerts generated by Module A (Prevention) or Module C (Aftermath)
CREATE TABLE IF NOT EXISTS public.guardian_alerts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    link_id UUID REFERENCES public.guardian_links(id) ON DELETE CASCADE,
    source_module TEXT NOT NULL, -- 'prevention' or 'aftermath'
    risk_type TEXT NOT NULL,
    risk_score NUMERIC NOT NULL,
    status TEXT NOT NULL DEFAULT 'unread', -- 'unread', 'read', 'actioned'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_guardian_alerts_link ON public.guardian_alerts(link_id);

-- Enable RLS (Service role will bypass this)
ALTER TABLE public.guardian_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guardian_alerts ENABLE ROW LEVEL SECURITY;
